export default {
  fallabalism: "knowledge does not require certainty",
  platonsim: "abstract objects exist",
  entity: "every entity falls into either abstract or concrete",
  "abstract objects": "every entity is either concrete or abstract",
  eternal: "without begining or end ",
  "libertarian free-will": "ability to have done otherwise",
  ubiquitius:
    "Being or seeming to be everywhere at the same time; omnipresent.",
  omnipresent: "Present everywhere simultaneously",
  omniscient: "Having total knowledge; knowing everything.",
  nominalism:
    "abstract concepts, general terms, or universals have no independent existence but exist only as names",
  universalism: "christians who believe all people will be eventually saved",
  universals:
    "Including, relating to, or affecting all members of the class or group",
  pantheism: "worship all gods",
  panentheism: "all things are a contained in god",
  deism: "god created universe and set it up, but does not intervene",
  dualism: "seperation of mind/matter; mind/body can function seperately",
  neoplatonism: "platonism + aristotelianism + oriental mysticism ",
  ultimate:
    "last in series/process/progression (syn: last); eventual; fundemental; elemental;",
  fundemental: "of or relating to the foundation or base",
  ontology: "The branch of metaphysics that deals with the nature of being.",
  teleology: "natural phenomena",
  epistemology: "nature of knowing",
  nature: "the material world and its phenomena",
  fact: "what the world is made of?",
  sophistry: "Plausible but fallacious argumentation.",
  "psr (principle sufficient reasoning)":
    "everything must have a reason, cause, or ground.",
  incompatibilist: "determinism is incompatible with free-will",
  compatibilist: "determinism is compatibile with free-will",
  evidentialism:
    "justified to believe if and only if you have evidence that supports your belief",
  indeterminism:
    "unpredictability; some events (human actions / decisions) have no cause",
  concequentialist: "normative properties depend only on consequences",
  coherintist:
    " the coherence theory of truth; and the coherence theory of justification.",
  cause: "The producer of an effect, result, or consequence.",
  explanation: "The act or process of explaining.; Something that explains.",
  "epistimology vs ontology": "e: ways we know things, o: the way things are",
  "coherence theory of truth": "",
  "coherence theory of justification": "",
  "prediction vs postdiction": "",
  pragmatist: " ",
  "pascals wager":
    " It posits that humans bet with their lives that God either exists or does not.",
  etymology: " ",
  "leplasses demon": " ",
  "tertiary structure": " ",
  "reflexive?": " ",
  "cartesian certainty": " ",
  fatalism: " ",
  gnosis: " ",
  "euthepro delema?": " ",
  structuralist: "",
  "abductive vs deductive": "",
  "abduction (abductive argument)": "",
  inductive: " ",
  contadictions: "",
  "synthetic/analytic disctinction": "",
  "concrete objects?": "",
  "dualism vs nominalism": "",
  "Anarcho-syndicalism": "",
  explication: "",
  primitives: "",
  "litnus test": "",
  paraconsistent: "",
  zoroastrianism: "",
  axiom: "",
  "pascals wager": "",
  "problem of undertermination": "",
  "ravens paradox": "",
  "gettier cases": "",
  "platonic form: ": "",
  "pauli exclusion principle": "",
};
